name: Latest repo workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
